### ISSUE TITLE
Issue with task list

### ISSUE THREAD

**Issue by roarwrecker** [roarwrecker/test#4]
Add content to readme.md:
- [ ] Write a short description about the project.
- [ ] List all dependencies.
- [ ] Write a "How-To" for installing the project
